TOKEN = "AquiVaLaKeyDelBot"
PREFIX = "!"
DB_PATH = "data/pablito.db"
ADMIN_IDS = []
LOG_CHANNEL_ID = 0
VOICE_CATEGORY_ID = 0
VOICE_CREATOR_ID = 0
POLL_EMOJIS = ["1️⃣", "2️⃣", "3️⃣", "4️⃣", "5️⃣", "6️⃣", "7️⃣", "8️⃣", "9️⃣", "🔟"]
COMMAND_COOLDOWN = 3
